"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts (default: true)
add_newline = false

format = """
$time\
[](fg:color_1 bg:color_2)\
$directory\
[](fg:color_2 bg:color_3)\
$git_branch\
$git_state\
$git_status\
[](fg:color_3)\
$status\
$cmd_duration\
$fill\
$line_break\
$character"""

palette = 'tomsquest'

[palettes.tomsquest]
color_1 = '#C9C3E6'
color_2 = '#E4D6F9'
color_3 = '#FFC5E4'
color_text = '#444444'

#[character]
#success_symbol = "[❯](color_green)"
#error_symbol = "[❗](color_red)"

[time]
disabled = false # the module is disabled by default
format = '[ $time ]($style)'
style = "bold fg:color_text bg:color_1"

[directory]
truncate_to_repo = false
format = "[ $path ]($style)"
style = "bold fg:color_text bg:color_2"

[fill]
symbol = '─'
style = 'white'

[git_branch]
format = '[ $branch ]($style)'
style = "bold fg:color_text bg:color_3"

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bold fg:color_text bg:color_3"
# Do not show stashed
stashed = ""
# Add the count
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'

[git_state]
style = "black"

[status]
disabled = false # the module is disabled by default
format = '[ $status ]($style)'
style = 'bold red'
pipestatus = true
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style)'

[cmd_duration]
format = '[ took $duration ]($style)'
style = "bright white"
min_time = 30_000
